Attempt to use eventStore (EventStore.JVM {scala}) technology causes java.lang.NoClassDefFoundError: eventstore/tcp/ConnectionActor$$anonfun$rcvConnected$1 on micronaut - https://stackoverflow.com/questions/33334456/flink-scala-version-conflict as a test - kafka was fully disabled in build.gradle - still causing same issue